version: "3"
services:
  nginx:
    build: nginx/ 
    image: nginx:latest
    container_name: production-nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - socks:/socks
  django:
    build: django/
    image: django:latest
    container_name: django-application
    command: gunicorn --workers 3 --bind unix:/socks/mysite.sock mysite.wsgi:application
    depends_on:
      - nginx
    volumes:
      - socks:/socks
volumes:
    socks: {}
